name: publish

on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v4
      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies and Build
        run: |
          yarn install
          yarn build
      - name: Semantic Release
        run: |
          yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
