name: publish

on:
  release:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Yarn install, build, and test
        run: |
          yarn install
          yarn test:cov

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: Yarn install & Build
        run: |
          yarn install
          yarn build
      - name: Publish to NPM Registry
        run: npm publish
        if: github.event.action == 'created'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
